# example workflow for Black Duck scans using the Bridge CLI
name: bd-bridge-cli

on:
  push:
    branches: [ main, master, stage, release ]
  pull_request:
    branches: [ main, master, stage, release ]
  workflow_dispatch:

jobs:
  blackduck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: microsoft
        cache: maven
    - name: Maven Build
      run: mvn -B -DskipTests package
    - name: Black Duck Scan
      env:
        BRIDGE_BLACKDUCK_URL: ${{ vars.BLACKDUCK_URL }}
        BRIDGE_BLACKDUCK_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
        DETECT_PROJECT_NAME: chuckaude-${{ github.event.repository.name }}
        DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
        DETECT_CODE_LOCATION_NAME: chuckaude-${{ github.event.repository.name }}-${{ github.ref_name }}
        DETECT_POLICY_CHECK_FAIL_ON_SEVERITIES: BLOCKER
        DETECT_EXCLUDED_DETECTOR_TYPES: GIT
      run: |
        curl -fLsS -o bridge.zip ${{ vars.BRIDGECLI_LINUX64 }} && unzip -qo -d $RUNNER_TEMP bridge.zip && rm -f bridge.zip
        $RUNNER_TEMP/synopsys-bridge --verbose --stage blackduck
