# example workflow for Black Duck scans using the Detect Action
# https://github.com/marketplace/actions/detect-rapid-scan-action
name: bd-detect-action

on:
  push:
    branches: [ main, master, stage, release ]
  pull_request:
    branches: [ main, master, stage, release ]
  workflow_dispatch:

jobs:
  blackduck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: microsoft
        cache: maven
    - name: Maven Build
      run: mvn -B -DskipTests package
    - name: Black Duck Scan
      uses: synopsys-sig/detect-action@v0.3.4
      env:
        DETECT_PROJECT_NAME: chuckaude-${{ github.event.repository.name }}
        DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
        DETECT_CODE_LOCATION_NAME: chuckaude-${{ github.event.repository.name }}-${{ github.ref_name }}
        DETECT_EXCLUDED_DETECTOR_TYPES: GIT
      with:
        blackduck-url: ${{ vars.BLACKDUCK_URL }}
        blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
        detect-version: 8.6.0
        scan-mode: INTELLIGENT
        github-token: ${{ secrets.GITHUB_TOKEN }}
